### ISSUE TITLE
Docker Compose breaks

### ISSUE THREAD

**Issue by g12n** [jure/pubsweet-blogger#1]
The Docker Compose Build breaks, while starting database.

On Mac:
Docker version 18.09.2, build 6247962

`````
Starting pubsweet-blogger_db_1 ... done
Attaching to pubsweet-blogger_db_1
db_1   | 2019-05-08 06:42:08.532 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1   | 2019-05-08 06:42:08.533 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1   | 2019-05-08 06:42:08.540 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1   | 2019-05-08 06:42:08.696 UTC [1] FATAL:  could not open directory "pg_tblspc": No such file or directory
db_1   | 2019-05-08 06:42:08.701 UTC [1] LOG:  database system is shut down
pubsweet-blogger_db_1 exited with code 1
`````

<img width="802" alt="docker-compose-break" src="https://user-images.githubusercontent.com/57556/57356458-c19bcd80-7170-11e9-8443-f1ed889f172a.png">

**Comment by kafkaliu** [comment]
Same problem I met

**Comment by jure** [comment]
For some reason I did not get a notification about this issue, so apologies for responding late! It was a silly `data/postgres` folder lingering around. Fixed now.
